/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tap_u3pf;

import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.io.FileOutputStream;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Shimishumi
 */
public class Decidir extends javax.swing.JFrame {
private String urlWS="http://localhost:8080/TAP_U3MPF/webresources/bd/";
private String us; 
private int size;
/**
     * Creates new form Decidir
     */
  //  Inicio i= new Inicio();
//private String us=;
    public Decidir() {
       
   
    }
    public Decidir(String usr){
    this.us=usr;
     initComponents();
        this.setLocationRelativeTo(null);
        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
        
        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        //Base 64 BITS transformar las imagenes
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        //jButton12.setVisible(false);
        //jButton13.setVisible(false);
        //jButton14.setVisible(false);
        //jButton15.setVisible(false);
        //jButton16.setVisible(false);
        //jButton17.setVisible(false);
    jPanel4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 218, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 440, 140));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Favoritos");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, 40));

        jButton12.setBackground(new java.awt.Color(204, 0, 51));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("X");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 470, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Code Bold", 1, 14)); // NOI18N
        jLabel14.setText("Ingrese palabras clave en la barra de busqueda");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 7, -1, -1));

        jTextField7.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 350, 30));

        jButton10.setBackground(new java.awt.Color(51, 204, 255));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Buscar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 53, -1, 30));

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("X");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 140));

        jButton13.setBackground(new java.awt.Color(51, 204, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Generar PDF");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 130, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 340));

        jLabel5.setFont(new java.awt.Font("Code Bold", 0, 14)); // NOI18N
        jLabel5.setText("Agregar lugares");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 130, 20));

        jLabel4.setFont(new java.awt.Font("Code Bold", 0, 14)); // NOI18N
        jLabel4.setText("Cerrar sesión");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 110, 20));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/nuevoLugar.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 90, 80));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Fav.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 100, 70));

        jLabel3.setFont(new java.awt.Font("Code Bold", 0, 14)); // NOI18N
        jLabel3.setText("Ver favoritos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 110, 40));

        jLabel6.setFont(new java.awt.Font("Code Bold", 0, 14)); // NOI18N
        jLabel6.setText("Buscar Lugares");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 130, 20));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Por favor, ingrese los datos solicitados");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 50));

        jLabel8.setText("ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel9.setText("Nombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel10.setText("Foto");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel11.setText("Dirección");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel12.setText("Horario");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel13.setText("Categoría");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 210, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 210, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 170, -1));

        jButton9.setBackground(new java.awt.Color(51, 204, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Registrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 400, 430));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Lupa.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 90, 70));

        jLabel2.setFont(new java.awt.Font("Code Bold", 0, 36)); // NOI18N
        jLabel2.setText("¿Qué desea hacer?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 360, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/LogOut.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 90, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Party rl2.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(310, 179));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Comida rl.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(310, 179));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/deporte rl2.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(310, 179));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Cultura rl.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(310, 179));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 650, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Seleccionar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 860, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Diversión
         JSONArray jar=new JSONArray();
            String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("categoria","Diversion");  
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
    String respuesta= target.path("cate").queryParam("log",jsonEnviar).request(MediaType.APPLICATION_JSON).get(String.class);
    try {      
        JSONObject jsr=(JSONObject)(new JSONParser()).parse(respuesta);
        jar=(JSONArray)jsr.get("resultado");
        if(!jar.isEmpty()){
      for(int i=0;i<jar.size();i++){
        JSONObject obj=(JSONObject)jar.get(i);
         new Lugar(us,obj.get("id").toString(),obj.get("nombre").toString(),obj.get("foto").toString(),obj.get("direccion").toString(),obj.get("horario").toString()).setVisible(true);
       
      }
    
        
    } 
       
    } catch (ParseException ex) {
        Logger.getLogger(Decidir.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Comida
            JSONArray jar=new JSONArray();
            String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("categoria","Comida");  
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
    String respuesta= target.path("cate").queryParam("log",jsonEnviar).request(MediaType.APPLICATION_JSON).get(String.class);
    try {      
        JSONObject jsr=(JSONObject)(new JSONParser()).parse(respuesta);
        jar=(JSONArray)jsr.get("resultado");
        if(!jar.isEmpty()){
      for(int i=0;i<jar.size();i++){
        JSONObject obj=(JSONObject)jar.get(i);
         new Lugar(us,obj.get("id").toString(),obj.get("nombre").toString(),obj.get("foto").toString(),obj.get("direccion").toString(),obj.get("horario").toString()).setVisible(true);
       
      }
    
        
    } 
       
    } catch (ParseException ex) {
        Logger.getLogger(Decidir.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Deporte
        JSONArray jar=new JSONArray();
        String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("categoria","Deportes");  
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
    String respuesta= target.path("cate").queryParam("log",jsonEnviar).request(MediaType.APPLICATION_JSON).get(String.class);
    try {      
        JSONObject jsr=(JSONObject)(new JSONParser()).parse(respuesta);
        jar=(JSONArray)jsr.get("resultado");
        if(!jar.isEmpty()){
      for(int i=0;i<jar.size();i++){
        JSONObject obj=(JSONObject)jar.get(i);
         new Lugar(us,obj.get("id").toString(),obj.get("nombre").toString(),obj.get("foto").toString(),obj.get("direccion").toString(),obj.get("horario").toString()).setVisible(true);
       
      }
    
        
    } 
       
    } catch (ParseException ex) {
        Logger.getLogger(Decidir.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Cultura
        JSONArray jar=new JSONArray();
            String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("categoria","Cultura");  
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
    String respuesta= target.path("cate").queryParam("log",jsonEnviar).request(MediaType.APPLICATION_JSON).get(String.class);
    try {      
        JSONObject jsr=(JSONObject)(new JSONParser()).parse(respuesta);
        jar=(JSONArray)jsr.get("resultado");
        if(!jar.isEmpty()){
      for(int i=0;i<jar.size();i++){
        JSONObject obj=(JSONObject)jar.get(i);
         new Lugar(us,obj.get("id").toString(),obj.get("nombre").toString(),obj.get("foto").toString(),obj.get("direccion").toString(),obj.get("horario").toString()).setVisible(true);
       
      }
    
        
    } 
       
    } catch (ParseException ex) {
        Logger.getLogger(Decidir.class.getName()).log(Level.SEVERE, null, ex);
    }
    ////////////////////Ver si esta vacio y si no, abrir///////////////////7
      
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // VER FAVORITOS
        jPanel1.setVisible(false);
        jPanel4.setVisible(true);
       String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("usuario", us);  
        //System.out.println(us);
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
    String respuesta= target.path("VerFavs").queryParam("log",jsonEnviar).request(MediaType.APPLICATION_JSON).get(String.class);
    try {      
        JSONObject jsr=(JSONObject)(new JSONParser()).parse(respuesta);
        JSONArray jar=(JSONArray)jsr.get("resultado");
        //System.out.println(jar);
        int row=0,col=0;       
        for(int i=0;i<jar.size();i++){
        JSONObject obj=(JSONObject)jar.get(i);
        
        jTable2.setValueAt(obj.get("nombre").toString(), row, 0);
           jTable2.setValueAt(obj.get("dire").toString(), row, 1);
           row++;
        }
    } catch (ParseException ex) {
        Logger.getLogger(Decidir.class.getName()).log(Level.SEVERE, null, ex);
    }
         jPanel1.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Cerrar sesión
        String ans="";
        JSONObject jobj= new JSONObject();
        Inicio i= new Inicio(); 
         jobj.put("usuario", i.usr);
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
        String respuesta= target.path("LogOut").queryParam("log",jsonEnviar).request("application/json").get(String.class);
        this.hide();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Agregar lugar, aquí viene lo bueno.
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // BOTON REGISTRAR LUGAR jajaja me estoy divirtiendo mucho en este lugar equisdedededede
        jPanel2.setVisible(false);
        String ans="";
        JSONObject jobj= new JSONObject();
        jobj.put("id", jTextField1.getText());
        jobj.put("nombre",jTextField2.getText());
        jobj.put("foto", jTextField3.getText());
        jobj.put("direccion", jTextField4.getText());
        jobj.put("horario", jTextField5.getText());
        jobj.put("categoria", jTextField6.getText());
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
        String respuesta= target.path("NuevoLugar").queryParam("log",jsonEnviar).request("application/json").get(String.class);
       //Limpiar los textfield
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jPanel1.setVisible(true);
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Buscar Lugares
      jPanel3.setVisible(true);
      jPanel2.setVisible(false);
      jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // BTNT cerrar del panel
            jPanel3.setVisible(false);
            jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // BTN buscar del panel buscar
      String ans="";
       // JSONArray ja= new JSONArray();
        JSONObject jobj= new JSONObject();
        jobj.put("palabras", jTextField7.getText());
        String jsonEnviar = jobj.toString().replace("{","%7B").replace("}","%7D");
        Client client =  ClientBuilder.newClient();
        WebTarget target = client.target(urlWS);
        String respuesta= target.path("Buscar").queryParam("log",jsonEnviar).request(MediaType.TEXT_PLAIN).get(String.class);  
        //Aquí empieza la locura... procesar respuesta
        //System.out.println(respuesta); 
        
            
             //JSONArray jsonrespuesta=(JSONArray)(new JSONParser()).parse(respuesta);
              
              
           //Perdoneme Amaro por esta vida tan loca...
     
     //int s=0;     
     //for(int i=0;i<respuesta.length();i++){
     //char c=respuesta.charAt(i);
     //String n="",f="";
     //if(c==':'){if(s==2){s=0;}else{s++;}
    //i++; continue;
    // } if(s==1){n+=c;}
    // if(s==2){f+=c;}
      //         JSONObject obj= new JSONObject();
     
    // }
 

            //System.out.println(jabjr.toString());
   String n="",f=""; int s=0; int r=0;
   int row=0,col=0;
   for(int i=0;i<respuesta.length();i++){
   char c= respuesta.charAt(i); 
   if(c=='*'){s++;continue;}
   if(s==0){n+=c;}
   if(s==1){if(c=='!'){}else{f+=c;}}
   if(c=='!'){s=0;
           jTable1.setValueAt(n, row, 0);
           jTable1.setValueAt(f, row, 1);
           row++;size++;
   //r++;
       /*switch(r)
               {
           case 0:
               jButton12.setVisible(true);
             jButton12.setText(n);
           jButton12.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton12.setForeground(new java.awt.Color(255, 255, 255));  
               break;
           case 1:
               jButton13.setVisible(true);
               jButton13.setText(n);
           jButton13.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton13.setForeground(new java.awt.Color(255, 255, 255));
               break;
           case 2:
               jButton14.setVisible(false);
               jButton14.setText(n);
           jButton14.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton14.setForeground(new java.awt.Color(255, 255, 255));
               break;
           case 3:
               jButton15.setVisible(false);
               jButton15.setText(n);
           jButton15.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton15.setForeground(new java.awt.Color(255, 255, 255));
               break;
           case 4:
               jButton16.setVisible(false);
               jButton16.setText(n);
           jButton16.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton16.setForeground(new java.awt.Color(255, 255, 255));
               break;
           case 5:
               jButton17.setVisible(false);
               jButton17.setText(n);
           jButton17.setFont(new java.awt.Font("Tahoma", 0, 16));
           jButton17.setForeground(new java.awt.Color(255, 255, 255));
               break;
   
       }*/
   n="";f="";} //jPanel4.repaint();
    
   } 
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        
        
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
          jTable1.setValueAt("", 0, 0);
           jTable1.setValueAt("", 0, 1);
              jTable1.setValueAt("", 1, 0);
           jTable1.setValueAt("", 1, 1);
              jTable1.setValueAt("", 2, 0);
           jTable1.setValueAt("",2, 1);
              jTable1.setValueAt("",3, 0);
           jTable1.setValueAt("", 3, 1);
              jTable1.setValueAt("", 4, 0);
           jTable1.setValueAt("", 4, 1);
              jTable1.setValueAt("", 5, 0);
           jTable1.setValueAt("", 5, 1);
              size=0;
        jTable1.repaint();
        jTable1.updateUI();
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // Generar PDF
        //Juar Juar Juar ya me cansé amiiigoooosss
        //Solicitud
         
        ///GENERAR EL PDF con los datos yaaa////
        
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream("Lugares.pdf"));
            doc.open();
            //Imagen
            //Image img = Image.getInstance(fieldImg.getText());
            //img.scaleToFit(50, 50);
            // Texto
            Paragraph parrafo = new Paragraph("Gracias por utiizar Sherlock");
            Paragraph parrafo2 = new Paragraph("\nResultados de la busqueda:");
            Paragraph parrafo3 = new Paragraph("\n");
            // Tabla
            PdfPTable table = new PdfPTable(2); // 3 columnas
            // Theader
            //table.addCell(new Phrase("Img", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.COURIER, 18, com.itextpdf.text.Font.BOLD)));
            table.addCell(new Phrase("Nombre", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.COURIER, 18, com.itextpdf.text.Font.BOLD)));
            table.addCell(new Phrase("Direccion", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.COURIER, 18, com.itextpdf.text.Font.BOLD)));
               //Ciclo para los datos
            for(int i=0;i<size;i++){
            
            table.addCell(jTable1.getValueAt(i, 0).toString());
            table.addCell(jTable1.getValueAt(i, 1).toString());
            
            }   
// Tbody
            
            
            // Agregar todo
           // doc.add(img);
            doc.add(parrafo);
            doc.add(parrafo2);
            doc.add(parrafo3);
            doc.add(table);
            doc.close();
            // Success
            JOptionPane.showMessageDialog(null, "Generado");
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "No se genero");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decidir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decidir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decidir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decidir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decidir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
